### ISSUE TITLE
pam_zfscrypt.c Comments Slightly Confusing

### ISSUE THREAD

**Issue by rlaager** [BenKerry/zfscrypt#12]
In `pam_zfscrypt.c`, you have comments that look like this:

```
/*
 * No-op
 *
 * We could have many more information of the user other then password
and username.
 * These are the credentials. For example, a kerberos ticket. Here we
establish those
 * and make them visible to the application.
 */
```

I assume the second bit of text in each of those is the PAM description. It might make sense to call that out more explicitly, as I found the switch a little jarring when reading. Perhaps something like:

```
/*
 * PAM describes this function as:
 * ...
 *
 * In zfscrypt, this is a no-op.
 */
```

or flip that around, if you like the current order.

**Comment by BenKerry** [comment]
These comments are leftovers from a tutorial. They definitely need a rewrite.
