### ISSUE TITLE
@BenKerry email address hidden and does not accept mail

### ISSUE THREAD

**Issue by rlaager** [BenKerry/zfscrypt#13]
Your email address is being hidden by GitHub, so your commits all look like this::

```
commit 9b353921abb6d8b672e2e1ce5235c346af5f3dd0
Author: Ben Kerry <25612144+BenKerry@users.noreply.github.com>
Date:   Sat Nov 30 19:48:19 2019 +0000

    Add missing step in readme on how to setup a new user

    Signed-off-by: Ben Kerry <25612144+BenKerry@users.noreply.github.com>
```

If that's intentional, that's one thing, though I wouldn't recommend it. If it's not, you should change that in your GitHub settings or whatever, so that future commits have a real email address.

I tried to email this to you, but that email address doesn't work. I guess that's somewhat expected, since it has "noreply" in it.

**Comment by BenKerry** [comment]
I see you have a public email on your profile. Is spam a problem for you?

**Comment by rlaager** [comment]
I use my email publicly all over the place, so I can't speak to whether GitHub by itself creates a spam problem. I certainly get spam in general.

**Comment by rlaager** [comment]
FWIW, you could certainly setup a second email address and forward it.

**Comment by BenKerry** [comment]
I've added a mail address to my profile now.
