### ISSUE TITLE
zfscrypt_utils.c Licenses?

### ISSUE THREAD

**Issue by rlaager** [BenKerry/zfscrypt#4]
Various functions in zfscrypt_utils.c were copied from other projects, but it's not clear what their licenses are or whether they are compatible with the top-level LICENSE.

**Comment by BenKerry** [comment]
systmed is GPLv2 licensed so probably not compatible at all. But I'm inexperienced with this things. How should it be handled in your opinion?

Thanks for all your feedback by the way 👍 I will look at your pull requests tomorrow.

**Comment by rlaager** [comment]
For free_ptr(), I would take the position that it is so trivial that it cannot be copyrightable. There is basically no other way to write that function.

The close_file() and close_fd() do not seem to exist in current systemd, in the files you referenced. BTW, the files you referenced are LGPL-2.1+, not GPL-2. They have code to close FILEs and fd, but the code looks nothing like this. Did you copy them from some older version? I'm not 100% sure what this assert is about. It seems to be checking that the call either succeeded or set errno to something other than EBADF. But in you're case, you're ignore errno, anyway, right? I don't know why `err >=0` rather than `err == 0`, which is what the man page documents as the return value (on Linux). If I were you, I might just "rewrite" them as follows, as the remaining bits are probably not copyrightable, being trivial and essentially the only possible way to write it:

```
void close_file(FILE** file) {
    if (*file != NULL) {
        const int err = fclose(*file);
        if (err != 0) {
            // TODO: Log an error using your logging function.
        }
    }
}

void close_fd(int const* fd) {
    if (*fd >= 0) {
        const int err = close(*fd);
        if (err != 0) {
            // TODO: Log an error using your logging function.
        }
    }
}
```

Then I'd just remove the references to copying them from systemd.

For drop_filesystem_cache(), just drop the comment. You didn't copy the code. You rewrote the same idea in C. In general, an argument would reasonably be made that something is a derivative work when you just port it from one language to another, but in this case, you're opening a file in /proc and writing a single character value to it. There's no other way to do that, so every implementation is going to look like that. You could also switch from fopen/fprintf/fclose to open/write/close, if you wanted.

For secure_free(), you should document why you have the secure_memset. Such a comment existed in the original code. It was not obvious to me, and I was originally going to suggest you remove secure_memset, which would have been bad. That might be the only non-trivial thing in here.

However, if you don't care about portability to non-Linux (and presumably you don't, given the drop caches code is Linux-specific), you could replace that secure_memset() with explicit_bzero(). At that point, I think everything you copied is sufficiently trivial to not really be copyrightable... calling malloc() and then mlock() isn't particularly creative. So then I'd feel okay removing the comments about fscrypt and calling it a day.
