### ISSUE TITLE
Dropping Filesystem Caches is Undesirable

### ISSUE THREAD

**Issue by rlaager** [BenKerry/zfscrypt#8]
Is it actually necessary to call drop_filesystem_cache()? Isn't unmounting and unloading the key sufficient? Dropping the filesystem caches every time a user logs out is really heavy-handed if the machine is shared in any way. It would be nice to avoid doing this at all.

**Comment by BenKerry** [comment]
Not sure. fscrypt does it, so I did it too. They provided the following comment in the [source](https://github.com/google/fscrypt/blob/master/security/cache.go#L32):

> "2" just frees the reclaimable inodes and dentries. The associated
> pages to these inodes will be freed. We do not need to free the
> entire pagecache (as this will severely impact performance).

**Comment by rlaager** [comment]
I've posted to zfs-devel. Let's see what we hear back from there.

**Comment by rlaager** [comment]
Tom Caputi, the author of ZFS encryption, responded to me off-list. To summarize what he said: normal Linux permission checks should be sufficient here, reclaiming the cache entries doesn't really buy more than that as it doesn't zero things from memory before freeing them, but you may want to keep it even though it doesn't help much.

**Comment by rlaager** [comment]
If you do elect to keep this, it might be better to rename the function. drop_filesystem_cache() sounds really heavy-handed and was (as you see here) confusing me initially into thinking it was dropping more than it is. Maybe something like free_reclaimable_inodes() or something.

**Comment by BenKerry** [comment]
Alight. Thanks for clarifying that. `free_reclaimable_inodes` sounds good to me.

**Comment by rlaager** [comment]
Just for the record, here is the full response from Tom, now that I've had a chance to confirm I have his permission to post this:

> This is probably a case where the best practice is to do it, but it
> probably doesn't actually help that much. As far as I am aware, the
> inodes and dentries shouldnt be accessible anymore due to Linux
> permissions, unless there is a bug. The ZFS native encryption
> implementation only provides at-rest encryption protection. It does
> not claim to provide any more protection to data that is in memory
> than the Linux permission system can provide. This is because, at some
> point, the data needs to be decrypted in RAM to be useful to an
> application so anything that can access the system's raw memory will
> be able to read this data whether or not the keys are loaded.
> 
> That being said, there are a couple of places where we do our best to
> protect against attacks. The biggest example of this is that we zero
> out encryption keys before freeing them. However, the Linux kernel
> will not do this for inodes and dentries even if we tell it to free
> them, so I'm not sure if dropping the caches will give us any real
> wins in this instance.

**Comment by BenKerry** [comment]
Alright.
