### ISSUE TITLE
Check secure_malloc() return values

### ISSUE THREAD

**Issue by rlaager** [BenKerry/zfscrypt#9]
secure_dup() needs to check the return value from secure_malloc() before calling memcpy(). You should check all your callers of secure_malloc(), and really regular malloc() too, to make sure they are checking its return value.

**Comment by rlaager** [comment]
@BenKerry Apparently your commits aren't automatically closing the issues because GitHub only supports "Fixes #9", not "Fixes issue #9": https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords

**Comment by BenKerry** [comment]
Good to known.
